<?php

namespace App\Containers\Comment\Providers;

use App\Containers\Article\Models\Article;
use App\Ship\Parents\Providers\MainProvider;
use Illuminate\Database\Eloquent\Relations\Relation;

/**
 * Class MainServiceProvider.
 *
 * The Main Service Provider of this container, it will be automatically registered in the framework.
 */
class MainServiceProvider extends MainProvider
{

    /**
     * Container Service Providers.
     *
     * @var array
     */
    public $serviceProviders = [
        // InternalServiceProviderExample::class,
    ];

    /**
     * Container Aliases
     *
     * @var  array
     */
    public $aliases = [
        // 'Foo' => Bar::class,
    ];

    /**
     * Register anything in the container.
     */
    public function register()
    {
        parent::register();

        // $this->app->bind(UserRepositoryInterface::class, UserRepository::class);
        // ...
    }

    public function boot()
    {
        Relation::morphMap([
            'articles' => Article::class,
        ]);
        //parent::boot(); // TODO: Change the autogenerated stub
    }
}
